rootProject.name = 'insightflow'

include(
    ':shared:common-web',
    ':services:ai-ops-core-service',
    ':services:gateway-service',
    ':services:policy-service',
    ':services:rate-limit-service',
    ':services:usage-service',
    ':services:billing-service',
    ':services:notification-service',
    ':services:recommendation-service'
)
